// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type RegisterRsp struct {
	Id    string `json:"id"`
	Email string `json:"email"`
	Phone string `json:"phone"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginRsp struct {
	Id    string `json:"id"`
	Email string `json:"email"`
	Phone string `json:"phone"`
}
